app/routes/api.py
from flask import Blueprint, redirect, url_for, flash
from flask_login import login_required, current_user
from app.forms import ShitForm
from app.models import Shit
from app import db
from datetime import datetime

bp = Blueprint('api', __name__)

@bp.route('/new_shit', methods=["POST"])
@login_required
def new_shit():
    form = ShitForm()
    
    if form.validate_on_submit():
        created_at = form.created_at.data if form.created_at.data else datetime.now()
        shit = Shit(
            shape=form.shape.data,
            quantity=form.quantity.data,
            colorID=form.colorID.data,
            dimension=form.dimension.data,
            level_of_satisfaction=form.level_of_satisfaction.data,
            userID=current_user.id,
            notes=form.notes.data,
            created_at=created_at
        )
        db.session.add(shit)
        db.session.commit()
        flash('Shit registration successful!', 'success')
        return redirect(url_for('main.home'))
    
    flash('Shit registration not successful!', 'error')
    return redirect(url_for('main.home'))

app/templates/logged/includes/add-modal.html
<!-- new modal -->
<div id="new-modal" class="modal">
    <div class="modal-inner">
        <span class="btn text modal-close" onclick="closeModal('new-modal')">&times;</span>
        <div style="margin: 50px 0; width: min(100%, 600px); height: 100%;">
            <h2>Record new shit</h2>
            <form method="POST" action="{{ url_for('api.new_shit') }}" class="basic-form">
                {{ add_modal_form.csrf_token }}
                <!-- Two-input container for time and rating fields -->
                <div class="two-inputs-container" style="grid-template-columns: 40% 60%;">
                    <div class="material-textfield">
                        {{ add_modal_form.created_at(id='created_at', class_='datetime-local') }}
                        {{ add_modal_form.created_at.label }}
                    </div>                    
                    <div class="rating-field">
                        <div class="feedback">
                            <div class="rating">
                                <input type="radio" name="level_of_satisfaction" id="rating-5" value="5">
                                <label for="rating-5"></label>
                                <input type="radio" name="level_of_satisfaction" id="rating-4" value="4">
                                <label for="rating-4"></label>
                                <input type="radio" name="level_of_satisfaction" id="rating-3" value="3">
                                <label for="rating-3"></label>
                                <input type="radio" name="level_of_satisfaction" id="rating-2" value="2">
                                <label for="rating-2"></label>
                                <input type="radio" name="level_of_satisfaction" id="rating-1" value="1">
                                <label for="rating-1"></label>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- More options button and script -->
                <div style="display: flex; padding-bottom: 50px;" id="more-change">
                    <button type="button" class="btn text" id="more-btn" style="width: 50%; position: absolute; left: 0;">More options</button>
                    <script>
                        $('#more-btn').click(function(event) {
                            event.preventDefault(); // Prevent the form from submitting
                            $('.more').slideToggle();
                            $('#more-btn').text(function(i, text){
                                return text === "More options" ? "Less options" : "More options";
                            });
                            $('#more-change').css('display', function(){
                                return $('#more-change').css('display') === 'flex' ? 'block' : 'flex';
                            });
                        });
                        // Set default value for created_at
                        document.addEventListener('DOMContentLoaded', (event) => {
                            const now = new Date();
                            const year = now.getFullYear();
                            const month = String(now.getMonth() + 1).padStart(2, '0');
                            const day = String(now.getDate()).padStart(2, '0');
                            const hours = String(now.getHours()).padStart(2, '0');
                            const minutes = String(now.getMinutes()).padStart(2, '0');
                            const formattedDateTime = `${year}-${month}-${day}T${hours}:${minutes}`;
                            document.getElementById('created_at').value = formattedDateTime;
                        });
                    </script>
                    <div class="more basic-form" style="display: none; margin: 50px 0 25px 0">
                        <div class="input-container">
                            <div class="select">
                                <select id="colorID" name="colorID" class="select-text">
                                    <option selected value="" style="display: none;" disabled></option>
                                    {% for value, label in add_modal_form.colorID.choices %}
                                        <option value="{{ value }}">{{ label }}</option>
                                    {% endfor %}
                                </select>
                                <label for="colorID" class="select-label">{{ add_modal_form.colorID.label.text }}</label>
                            </div>
                        </div>
                        <div class="input-container">
                            <div class="select">
                                <select class="select-text" id="shape" name="shape">
                                    <option selected value="" style="display: none;" disabled></option>
                                    {% for value, label in add_modal_form.shape.choices %}
                                        <option value="{{ value }}">{{ label }}</option>
                                    {% endfor %}
                                </select>
                                <label for="shape" class="select-label">{{ add_modal_form.shape.label.text }}</label>
                            </div>
                        </div>
                        <div class="two-inputs-container">
                            <div class="material-textfield">
                                {{ add_modal_form.quantity.label }}
                                {{ add_modal_form.quantity() }}
                            </div>
                            <div class="material-textfield">
                                {{ add_modal_form.dimension.label }}
                                {{ add_modal_form.dimension() }}
                            </div>
                        </div>
                        <div class="input-container">
                            <div class="material-textfield">
                                {{ add_modal_form.notes() }}
                                {{ add_modal_form.notes.label }}
                            </div>
                        </div>
                    </div>
                    
                    <button type="submit" class="btn filled" style="width: 50%; position: absolute; right: 0;">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

app/templates/logged/includes/sidebar.html
<div class="sidebar">
	<div class="sidebar-inner">
		<a class="sidebar-link sidebar-desktop" id="home" href="/home">
			<span class="material-symbols-outlined">
				home
			</span>
			<span class="sidebar-link-text">Home</span>
		</a>
		<a class="sidebar-link" id="add" onclick="openModal('new-modal')"> <!-- TODO: highlight add btn -->
			<span class="material-symbols-outlined">
				add
			</span>
			<span class="sidebar-link-text">Add</span>
		</a>
		<a class="sidebar-link" id="settings" href="/settings">
			<span class="material-symbols-outlined">
				settings
			</span>
			<span class="sidebar-link-text">Settings</span>
		</a>
	</div>
</div>

<script>
	function closeModal(id) {
		document.getElementById(id).style.display = "none";
	}
	function openModal(id) {
		document.getElementById(id).style.display = "flex";
	}
</script>

<script>
	// on scroll down hide / up show sidebar-link-text on mobile
	function nav(){
		if (window.innerWidth <= 600) {
			var prevScrollpos = window.pageYOffset;
			window.onscroll = function() {
				var currentScrollPos = window.pageYOffset;
				if (prevScrollpos > currentScrollPos || (window.innerHeight + window.pageYOffset) >= document.body.offsetHeight-1 || currentScrollPos < 10) {
					$(".sidebar-link-text").slideDown(300);
					$(".sidebar").css("height", "78px");
				} else {
					$(".sidebar-link-text").slideUp(300);
					$(".sidebar").css("height", "58px");
				}
				prevScrollpos = currentScrollPos;
			}
		} else {
			// default size
			$(".sidebar").css("height", "100%");
			$(".sidebar-link-text").show();
			window.onscroll = null;
		}
	}
	nav();
	window.onresize = function() {
		nav();
	};
</script>


		{% include "/logged/includes/add-modal.html" %}